### ISSUE TITLE
Day 2, line 61

### ISSUE THREAD

**Issue by aaditya25052002** [akash1520/learnTS#1]
In TypeScript, the type of an array is not explicitly assigned by default because TypeScript allows for flexibility in the type of elements that can be stored in an array.

**Comment by akash1520** [comment]
Thank you @aaditya25052002 for the information. Added it in the [commit #6370024](https://github.com/akash1520/learnTS/commit/6370024a74863f04c069d273ec3fdd8f8a15cb09) .
